Transform: AWS::Serverless-2016-10-31

Parameters:
  LambdaZipBucket:
    Type: String
    Default: notes-app-lambda-zipfiles
    Description: S3 bucket where the Lambda zip files are stored

Resources:
  NotesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  CreateNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: CreateNoteFunction
      CodeUri:
        Bucket: !Ref LambdaZipBucket
        Key: create-note.zip
      Handler: app.lambda_handler
      Runtime: python3.13
      MemorySize: 128
      Timeout: 30
      Tracing: Active
      Role: arn:aws:iam::670609912546:role/LabRole
      Environment:
        Variables:
          NOTESTABLE_TABLE_NAME: !Ref NotesTable
          NOTESTABLE_TABLE_ARN: !GetAtt NotesTable.Arn

  CreateNoteFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${CreateNoteFunction}

  ListNotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: ListNotesFunction
      CodeUri:
        Bucket: !Ref LambdaZipBucket
        Key: list-notes.zip
      Handler: app.lambda_handler
      Runtime: python3.13
      MemorySize: 128
      Timeout: 30
      Tracing: Active
      Role: arn:aws:iam::670609912546:role/LabRole
      Environment:
        Variables:
          NOTESTABLE_TABLE_NAME: !Ref NotesTable
          NOTESTABLE_TABLE_ARN: !GetAtt NotesTable.Arn

  ListNotesFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${ListNotesFunction}

  DeleteNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: DeleteNoteFunction
      CodeUri:
        Bucket: !Ref LambdaZipBucket
        Key: delete-note.zip
      Handler: app.lambda_handler
      Runtime: python3.13
      MemorySize: 128
      Timeout: 30
      Tracing: Active
      Role: arn:aws:iam::670609912546:role/LabRole
      Environment:
        Variables:
          NOTESTABLE_TABLE_NAME: !Ref NotesTable
          NOTESTABLE_TABLE_ARN: !GetAtt NotesTable.Arn

  DeleteNoteFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${DeleteNoteFunction}

  UpdateNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: UpdateNoteFunction
      CodeUri:
        Bucket: !Ref LambdaZipBucket
        Key: update-note.zip
      Handler: app.lambda_handler
      Runtime: python3.13
      MemorySize: 128
      Timeout: 30
      Tracing: Active
      Role: arn:aws:iam::670609912546:role/LabRole
      Environment:
        Variables:
          NOTESTABLE_TABLE_NAME: !Ref NotesTable
          NOTESTABLE_TABLE_ARN: !GetAtt NotesTable.Arn

  UpdateNoteFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${UpdateNoteFunction}

  NotesApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: NotesApi
      StageName: Prod
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /notes:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ListNotesFunction.Arn}/invocations
              responses: {}
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateNoteFunction.Arn}/invocations
              responses: {}
            options:
              x-amazon-apigateway-integration:
                type: mock
                requestTemplates:
                  application/json: '{"statusCode": 200}'
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type'"
                      method.response.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
              responses:
                "200":
                  description: CORS response
                  headers:
                    Access-Control-Allow-Headers:
                      schema:
                        type: string
                    Access-Control-Allow-Methods:
                      schema:
                        type: string
                    Access-Control-Allow-Origin:
                      schema:
                        type: string
          /notes/{id}:
            put:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateNoteFunction.Arn}/invocations
              responses: {}
            delete:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteNoteFunction.Arn}/invocations
              responses: {}
            options:
              x-amazon-apigateway-integration:
                type: mock
                requestTemplates:
                  application/json: '{"statusCode": 200}'
                responses:
                  default:
                    statusCode: "200"
                    responseParameters:
                      method.response.header.Access-Control-Allow-Headers: "'Content-Type'"
                      method.response.header.Access-Control-Allow-Methods: "'GET,PUT,DELETE,OPTIONS'"
                      method.response.header.Access-Control-Allow-Origin: "'*'"
              responses:
                "200":
                  description: CORS response
                  headers:
                    Access-Control-Allow-Headers:
                      schema:
                        type: string
                    Access-Control-Allow-Methods:
                      schema:
                        type: string
                    Access-Control-Allow-Origin:
                      schema:
                        type: string
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Cors:
        MaxAge: 5
        AllowOrigin: '''*'''
        AllowHeaders: '''Content-Type'''
        AllowMethods: '''GET,POST,PUT,DELETE,OPTIONS'''

  CreateNoteFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CreateNoteFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${NotesApi}/*/*

  ListNotesFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ListNotesFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${NotesApi}/*/*

  DeleteNoteFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref DeleteNoteFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${NotesApi}/*/*

  UpdateNoteFunctionApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref UpdateNoteFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${NotesApi}/*/*

  NotesWebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-noteswebs-${AWS::AccountId}
      WebsiteConfiguration:
        IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  NotesWebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref NotesWebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub ${NotesWebsiteBucket.Arn}/*

Outputs:
  WebsiteURL:
    Description: URL of the S3 static website
    Value: !GetAtt NotesWebsiteBucket.WebsiteURL
  ApiUrl:
    Description: Base URL of the Notes API
    Value: !Sub https://${NotesApi}.execute-api.${AWS::Region}.amazonaws.com/Prod